[package]
name = "human-protocol-sdk"
version = "0.1.0"
edition = "2021"

[lib]
name = "human_protocol_sdk"
path = "src/main.rs"

[dependencies]
url = "2.4.1"
web3 = "0.19.0"
tokio = { version = "1.34.0", features = ["full", "macros"] }
secp256k1 = "0.28.0"
tracing-subscriber = "0.3.17"
dialoguer = {version = "0.11.0", features = ["fuzzy-select"]}
lazy_static = "1.4.0"
thiserror = "1.0.0"
pgp = "0.10.2"
rand = "0.8"
reqwest = { version = "0.11.22", features = ["json", "blocking"] }
serde_derive = "1.0.192"
serde_json = { version = "1.0.108" }
serde = { version = "1.0.192", features = ["derive"] }
serde_with = "3.4.0"
chrono = { version = "0.4", features = ["serde"] }
cynic = { version = "3.3.0", features = ["http-reqwest-blocking"] }
hex = "0.4.3"

[build-dependencies]
cynic-codegen = { version = "3.3.0" }

[dev-dependencies]
insta = "1.34.0"
