[tool.poetry]
name = "recording-oracle"
version = "0.1.0"
description = "Recording Oracle example for text span annotations"
authors = ["Marius Hamacher <marius.hamacher@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.108.0"
uvicorn = {extras = ["standard"], version = "^0.25.0"}
sqlalchemy = "^2.0.23"
psycopg2 = "^2.9.9"
apscheduler = "^3.10.4"
httpx = "^0.26.0"
aiohttp = "^3.9.1"
cryptography = "^41.0.7"
pyjwt = "^2.8.0"
human-protocol-sdk = "^1.1.19"
hmt-basemodels = "^0.2.7"
pygamma-agreement = {extras = ["cbc"], version = "^0.5.6"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
