[profile.default]
src = "src"
out = "abis"
libs = ["lib"]
via-ir=true
optimizer_runs = 10
gas_reports = ["*"]


[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
goerli = "https://rpc.ankr.com/eth_goerli"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismGoerli = "https://opt-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://rpc.ankr.com/polygon_mumbai"
gnosis = "https://rpc.gnosischain.com"
linea = "https://rpc.goerli.linea.build"
mantleTestnet = "https://rpc.testnet.mantle.xyz"
neonDevnet = "https://devnet.neonevm.org"
gnosisChiado = "https://rpc.chiadochain.net"

[etherscan]
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
arbitrumGoerli = { key = "${ETHERSCAN_API_KEY}" }
baseGoerli = { key = "${ETHERSCAN_API_KEY}" }
celoAlfajores = { key = "${ETHERSCAN_API_KEY}" }
scrollSepolia = { key = "${ETHERSCAN_API_KEY}" , url = "https://api-sepolia.scrollscan.dev/api" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config

