[profile.default]
src = 'contracts'
out = 'dist'
libs = ['../../node_modules/','lib']
test = 'test'
optimizer = true
optimizer-runs = 10_000_000
cache_path  = 'cache_forge'

#[rpc_endpoints]
#avalanche = "${AVALANCHE_RPC_URL}"
#mumbai = "${POLYGON_MUMBAI_RPC_URL}"
#moonbase = "${MOONBASE_RPC_URL}"
#
#[etherscan]
#mumbai = { key = "${MUMBAI_ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
#avalanche = { key = "${AVALANCHE_ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api" }
#moonbase = { key = "${MOONBASE_ETHERSCAN_API_KEY}", url = "https://api-moonbase.moonscan.io/api" }

[doc]
title = 'Human Governor Contracts'
ignore = ['contracts/hm-token/*.sol','contracts/vhm-token/*.sol']


