[profile.default]
src = "src"
out = "abis"
libs = ["lib"]
via-ir=true
optimizer_runs = 10
gas_reports = ["*"]


[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"


mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ETH_MAINNET_URL}"
goerli = "https://rpc.ankr.com/eth_goerli"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://rpc.ankr.com/polygon_mumbai"
bnbTesnet=""
moonBaseAlpha=""
avalancheFuji=""
celoAlfajores=""


[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
bnbTesnet = { key = "${ETHERSCAN_API_KEY}" }
moonBaseAlpha = { key = "${ETHERSCAN_API_KEY}" }
avalancheFuji = { key = "${ETHERSCAN_API_KEY}" }
celoAlfajores = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config

